# A Two-Bit Solution to the Exercism Roman Numeral Problem
Note:
- This program does not work if the number has greater than four digits.
  - Of course, that's actually a good question. How did the Romans deal with numbers
  greater than 2,000? 
     - It's really unwieldy to write MMMMMMMMM. 
     - One solution the Romans had, write V but with a bar over it, to indicate 5,000 [Source](http://www.novaroma.org/via_romana/numbers.html)
     - What about numbers in the tens of thousands or hundreds of thousands? What then?
       - According to [Wikipedia](https://en.wikipedia.org/wiki/Roman_numerals#Large_numbers), other folks have worked out notation for huge numbers.
       - Still, good question: did the average Roman conceive of numbers larger than the thousands? They had rudimentary fractions, but it doesn't mean that they could conceive of numbers like 232.232323239 or 2.23 x 10**4232
- It creates four dictionaries.
- Perhaps there is a better way to resolve the 4 digit problem. 
- I might want to time this. 

In [17]:
import timeit
def roman_numerals(raw_input):
    str_input= str(raw_input).strip()
    unums = {'1': 'I','2': 'II', '3': 'III', 
            '4': 'IV', '5': 'V', '6': 'VI', 
             '7': 'VII', '8': 'VIII', 
             '9': 'IX','0':""}
    decems = {'1': 'X','2': 'XX', '3': 'XXX', 
            '4': 'XL', '5': 'L', '6': 'LX', 
             '7': 'LXX', '8': 'LXXX', 
             '9': 'XC','0':""}
    centums = {'1': 'C','2': 'CC', '3': 'CCC', 
            '4': 'CD', '5': 'D', '6': 'DC', 
             '7': 'DCC', '8': 'DCCC', 
             '9': 'CM','0':""}
    millums = {'1': 'M','2': 'MM', '3': 'MMM', 
            '4': 'MMMM', '5': 'MMMMM', '6': 'MMMMMM', 
             '7': 'MMMMMMM', '8': 'MMMMMMMM', 
             '9': 'MMMMMMMMM','0':""}
    if len(str_input) == 1:
        return unums[str_input]
    elif len(str_input) ==2:
        return decems[str_input[0]]+unums[str_input[1]]
    elif len(str_input) ==3:
        return centums[str_input[0]]+decems[str_input[1]]+unums[str_input[2]]
    elif len(str_input)==4:
        return millums[str_input[0]]+centums[str_input[1]]+decems[str_input[2]]+unums[str_input[3]]

## Some Test Runs

In [18]:
roman_numerals(55)

'LV'

In [19]:
roman_numerals(101)

'CI'

In [20]:
roman_numerals(99)

'XCIX'

In [21]:
roman_numerals(1530)

'MDXXX'

In [22]:
roman_numerals(1024)

'MXXIV'

In [23]:
roman_numerals(1)

'I'

# Bethany Solution
This is the solution created by Bethany Garcia.
- This solution takes advantage of Python string operations. * that does prints strings multiple times. Whee.
- This solution uses one dictionary.
- Let's time both and see how long they take.



In [37]:
ROMAN = {1:'I', 5:'V', 10:'X', 50:'L', 100:'C', 500:'D', 1000:'M'}

def numeral(num):
    new_num = [[1000, num - num%1000], 
               [100, num%1000 - num%100],
               [10, num%100 - num%10],
               [1, num%10]]

    for index, item in enumerate(new_num):
        if item[1] == 0: 
            new_num[index][1] = ''
            continue
        
        if item[1] == 1000:
           new_num[index][1] = ROMAN[1000] * (item[1]//1000) 
           
        else:
            if item[1]/item[0] == 9:
               new_num[index][1] = ROMAN[item[0]] + ROMAN[10*item[0]]
            elif item[1]/item[0] ==5:
                new_num[index][1] = ROMAN[5 * item[0]]
            elif item[1]/item[0] ==4:
                new_num[index][1] = ROMAN[1 * item[0]] + ROMAN[5 * item[0]]
            elif 9 > item[1]/item[0] > 5:
               new_num[index][1] = ROMAN[5 * item[0]] + ROMAN[1 * item[0]] * (item[1]//item[0] - 5)
            else:
               new_num[index][1] = ROMAN[1 * item[0]] * (item[1]//item[0])
               
    return ''.join((item[1] for item in new_num))

# Alan's Recursive Solution:
This is a solution that uses recursion. 

In [38]:
def roman_numerals_a(number):
	return tailRecursiveNumeral(number, '')
def tailRecursiveNumeral(number,R):
	#roman_tailRecursiveNumeral=R
	if number < 1:
		return R #if number is less than 1, return R
	elif number >= 1000:
		# if number is greater than or equal to 1000, add M to R, and subtract 1000 from the number. 
		return tailRecursiveNumeral(number-1000,R+'M')
	elif number+100>=1000:
		#if number plus 100 is greater than 1000, add C to R, and 
		#e.g. 900s --> CM add C now, add M in the next
		return tailRecursiveNumeral(number+100,R+'C')	
	elif number >= 500:
		return tailRecursiveNumeral(number-500,R+'D')
	elif number+100>=500:
		return tailRecursiveNumeral(number+100,R+'C')
	elif number >= 100:
		return tailRecursiveNumeral(number-100,R+'C')
	elif number+10>=100:
		return tailRecursiveNumeral(number+10,R+'X')
	elif number >= 50:
		return tailRecursiveNumeral(number-50,R+'L')
	elif number+10>=50:
		return tailRecursiveNumeral(number+10,R+'X')
	elif number >= 10:
		return tailRecursiveNumeral(number-10,R+'X')
	elif number+1>=10:
		return tailRecursiveNumeral(number+1,R+'I')
	elif number >= 5:
		return tailRecursiveNumeral(number-5,R+'V')
	elif number+1>=5:
		return tailRecursiveNumeral(number+1,R+'I')
	elif number > 0:
		return tailRecursiveNumeral(number-1, R+'I')

# Generator Solution
This solution is similar to the recursive solution but makes use of a generator.


In [55]:
def roman_numerals_g(number):
	return ''.join(roman_generator(number))
	

def roman_generator(number):
	#roman_tailRecursiveNumeral=R
	# if number < 1:
	#	return R #if number is less than 1, return R
	if number >= 1000:
		# if number is greater than or equal to 1000, add M to R, and subtract 1000 from the number. 
		yield "M"
		yield from roman_generator(number-1000)
	elif number+100>=1000:
		#if number plus 100 is greater than 1000, add C to R, and 
		#e.g. 900s --> CM add C now, add M in the next
		yield "C"
		yield from roman_generator(number+100)
	elif number >= 500:
	    yield "D"
	    yield from roman_generator(number-500)
	elif number+100>=500:
	    yield "C"
	    yield from roman_generator(number+100)
	elif number >= 100:
	    yield "C"
	    yield from roman_generator(number-100)
	elif number+10>=100:
	    yield "X"
	    yield from roman_generator(number+10)
	elif number >= 50:
	    yield "L"
	    yield from roman_generator(number-50)
	elif number+10>=50:
	    yield "X"
	    yield from roman_generator(number+10)
	elif number >= 10:
	    yield "X"
	    yield from roman_generator(number-10)
	elif number+1>=10:
	    yield "I"
	    yield from roman_generator(number+1)
	elif number >= 5:
	    yield "V"
	    yield from roman_generator(number-5)
	elif number+1>=5:
	    yield "I"
	    yield from roman_generator(number+1)
	elif number > 0:
	    yield "I"
	    yield from roman_generator(number-1)
	    


## Timeit Results
Here are the time it results.

### Bethany Solution, timeit results

In [69]:
% timeit roman_numerals

10000000 loops, best of 3: 31.6 ns per loop


### Arthur Solution, timeit results

In [67]:
% timeit numeral

10000000 loops, best of 3: 31.6 ns per loop


### Alan's Recursive Solution

In [66]:
% timeit roman_numerals_a

10000000 loops, best of 3: 31.5 ns per loop


### Generator Solution Based on Recursive Solution

In [65]:
% timeit roman_numerals_g

10000000 loops, best of 3: 33.9 ns per loop


### Numpy:

In [1]:
import numpy as np

In [15]:
tacboard = np.arange(9).reshape((3,3))
print(tacboard)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
print(tacboard.diagonal())
print(tacboard[::-1].diagonal(), '\n')

print(tacboard.T, '\n')
print(tacboard.T.T.T.T.T.T.diagonal(), '\n')

[0 4 8]
[6 4 2] 

[[0 3 6]
 [1 4 7]
 [2 5 8]] 

[0 4 8] 



In [6]:
tacboard.diagonal[0]

TypeError: 'builtin_function_or_method' object is not subscriptable